spring:
  graphql:
    graphiql:
      enabled: true

  datasource:
    driverClassName: ${DB_DRIVER:org.h2.Driver}
    password: ${DB_PASSWORD:password}
    username: ${DB_USERNAME:sa}
    url: ${DB_URL:jdbc:h2:mem:testdb}
  h2.console.enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: ${DB_DIALECT:org.hibernate.dialect.H2Dialect}
    properties.hibernate:
      format_sql: true
      show_sql: true
logging:
  level:
    org:
      springframework:
        web:
          cors: DEBUG
